export const SIGN_UP_WITH_EMAIL_PASS = "SIGN_UP_WITH_EMAIL_PASS"
export const SIGN_UP_WITH_GOOGLE = "SIGN_UP_WITH_GOOGLE"
export const SIGN_UP_WITH_FACEBOOK = "SIGN_UP_WITH_FACEBOOK"
export const SIGN_UP_WITH_NUMBER = "SIGN_UP_WITH_NUMBER"
export const SIGN_OUT = "SIGN_OUT"
export const RESET_PASS = "RESET_PASS"
export const SIGN_IN_WITH_EMAIL_PASS = "SIGN_IN_WITH_EMAIL_PASS"

