export const SIGN_UP_WITH_EMAIL_PASS = "SIGN_UP_WITH_EMAIL_PASS"
export const SIGN_OUT = "SIGN_OUT"
export const RESET_PASS = "RESET_PASS"
export const SIGN_IN_WITH_EMAIL_PASS = "SIGN_IN_WITH_EMAIL_PASS"
export const UPDATE_EMAIL = "UPDATE_EMAIL"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const SORT_SELECT = "SORT_SELECT"
export const FILTER_BY_PRICE = "FILTER_BY_PRICE"
export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_TO_WISHED = "ADD_TO_WISHED"
export const NEW_ARRIVALS = "NEW_ARRIVALS"




